language: node_js
node_js:
  - "10"

jobs:
  include:
    - name: test
      before_install:
        - npm install -g yarn
        - yarn install
      before_script:
        - docker pull kodebox/codechain:c6ca38e14dde18650e7fe36eb7c47213625a8d02
        - docker run -d -p 8080:8080 kodebox/codechain:c6ca38e14dde18650e7fe36eb7c47213625a8d02 --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0 --enable-devel-api
        - psql -c 'CREATE DATABASE "codechain-indexer-test";' -U postgres
        - psql -c "CREATE USER \"user\" WITH ENCRYPTED PASSWORD 'password';" -U postgres
        - docker ps -a
      script:
        - set -e
        - yarn run lint
        - NODE_ENV=test yarn migrate
        - yarn run test
services:
  - docker
  - postgresql
addons:
  postgresql: "9.4"
cache: yarn
