language: node_js
node_js:
  - "10"
  - "8"
before_script:
  - docker pull kodebox/codechain:4cea6ae32a2ac46c3a0ec877c383b36826c9d26f
  - docker run -d -p 8080:8080 kodebox/codechain:4cea6ae32a2ac46c3a0ec877c383b36826c9d26f --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0
  - docker ps -a
before_install:
  - yarn install
script:
  - yarn run lint
  - yarn run test
services:
  - docker
cache: yarn
