language: node_js
node_js:
  - "10"
  - "8"
before_install:
  - yarn install
  - yarn migrate
before_script:
  - docker pull kodebox/codechain:03ecfdf81f87f1cf579f862c9da8edd5faf7266d
  - docker run -d -p 8080:8080 kodebox/codechain:03ecfdf81f87f1cf579f862c9da8edd5faf7266d --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0
  - docker pull postgres:latest
  - docker run --name my_postgres -p 5432:5432 -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=codechain-indexer-test -d postgres
  - docker ps -a
script:
  - yarn run lint
  - yarn run test
services:
  - docker
cache: yarn
