language: node_js
node_js:
  - "10"
before_install:
  - yarn install
before_script:
  - docker pull kodebox/codechain:d669b841f36ada2ec509f62a35147243e00f1bdc
  - docker run -d -p 8080:8080 kodebox/codechain:d669b841f36ada2ec509f62a35147243e00f1bdc --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0 --enable-devel-api
  - psql -c 'CREATE DATABASE "codechain-indexer-test";' -U postgres
  - psql -c "CREATE USER \"user\" WITH ENCRYPTED PASSWORD 'password';" -U postgres
  - docker ps -a
script:
  - yarn run lint
  - NODE_ENV=test yarn migrate && yarn run test
services:
  - docker
  - postgresql
addons:
  postgresql: "9.4"
cache: yarn
