language: node_js
node_js:
  - "10"
before_install:
  - npm install -g yarn
  - yarn install
before_script:
  - docker pull kodebox/codechain:d669b841f36ada2ec509f62a35147243e00f1bdc
  - docker run -d -p 8080:8080 kodebox/codechain:d669b841f36ada2ec509f62a35147243e00f1bdc --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0 --enable-devel-api
  - psql -c 'CREATE DATABASE "codechain-indexer-test";' -U postgres
  - psql -c "CREATE USER \"user\" WITH ENCRYPTED PASSWORD 'password';" -U postgres
  - docker ps -a
script:
  - set -e
  - yarn run lint
  - NODE_ENV=test yarn migrate
  - yarn run test --testRegex compose-decompose.spec.ts
  - yarn run test --testRegex db-block-interface.spec.ts
  - yarn run test --testRegex log.spec.ts
  - yarn run test --testRegex mint-transfer.spec.ts
  - yarn run test --testRegex payment.spec.ts
  - yarn run test --testRegex pending-tx.spec.ts
  - yarn run test --testRegex snapshot.spec.ts
  - yarn run test --testRegex worker.spec.ts
services:
  - docker
  - postgresql
addons:
  postgresql: "9.4"
cache: yarn
