language: node_js
node_js:
  - "10"

jobs:
  include:
    - name: test
      before_install:
        - npm install -g yarn
        - yarn install
      before_script:
        - docker pull kodebox/codechain:b4e05e83b7c8ca21df677ccff26a2d11914b71e3
        - docker run -d -p 8080:8080 kodebox/codechain:b4e05e83b7c8ca21df677ccff26a2d11914b71e3 --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0 --enable-devel-api
        - psql -c 'CREATE DATABASE "codechain-indexer-test";' -U postgres
        - psql -c "CREATE USER \"user\" WITH ENCRYPTED PASSWORD 'password';" -U postgres
        - docker ps -a
      script:
        - set -e
        - yarn run lint
        - NODE_ENV=test yarn migrate
        - yarn run test
    - name: test-int
      before_install:
        - npm install -g yarn
        - yarn install
        - cd e2e-test
        - yarn install
      before_script:
        - yarn run pull-docker
        - psql -c "CREATE USER \"user\" WITH ENCRYPTED PASSWORD 'password';" -U postgres
        - psql -c 'CREATE DATABASE "codechain-indexer-test";' -U postgres
        - psql -c 'CREATE DATABASE "codechain-indexer-test-int";' -U postgres
      script:
        - set -e
        - yarn run lint
        - yarn run test
services:
  - docker
  - postgresql
addons:
  postgresql: "9.4"
cache: yarn
